cask_args appdir: '/Applications'

tap 'homebrew/cask'

brew 'coreutils'
brew 'git'
brew 'imagemagick'
brew 'php'
brew 'node'
brew 'speedtest_cli'
brew 'webkit2png'
brew 'wget'
brew 'youtube-dl'

cask 'caffeine'
cask 'google-chrome'
cask 'imageoptim'
cask 'imazing'
cask 'iterm2'
cask 'pocket-casts'
cask 'sequel-pro'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'vlc'